[phases.setup]
nixPkgs = ["icu", "openssl"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app/out"]

[start]
cmd = "ASPNETCORE_URLS=http://0.0.0.0:$PORT dotnet /app/out/socio.dll"
